[package]
name = "walkers-editor"
version = "0.1.0"
edition = "2021"

[dependencies]
walkers = "0.32.0"
eframe = { version = "*", default-features = false, features = [
	"glow",
	"default_fonts",
] }
reqwest = { version = "*", default-features = false, features = ["rustls-tls", "json", "blocking"] }
osm-parser = { version = "2.0", git = "https://github.com/Swarkin/osm-parser.git" }
webmercator_tiles = "1.0"
#osm-parser = { path = "../osm-parser" }
