[package]
name = "walkers-editor"
version = "0.1.0"
authors = ["Swarkin"]
repository = "https://github.com/Swarkin/walkers-editor"
readme = "README.md"
edition = "2024"
build = "build.rs"

[features]
debug = []

[dependencies]
walkers = "0.41.0"
eframe = { version = "*", default-features = false, features = ["glow", "default_fonts"] }
egui_extras = { version = "*", default-features = false, features = ["svg", "syntect"] }
ureq = { version = "3.0", default-features = false, features = ["rustls", "json", "gzip"] }
serde = { version = "1", features = ["derive"] }
quick-xml = { version = "0.38", features = ["serialize"] }
crossbeam-channel = "0.5"
osm-parser = { version = "*", git = "https://github.com/Swarkin/osm-parser.git" }
webmercator_tiles = "1.0"
lyon_tessellation = "1.0"

[build-dependencies]
winresource = "0.1"

[profile.release]
opt-level = 3
strip = true
lto = true
